---
- name: macOS Setup Playbook
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/packages.yml
    - vars/defaults.yml

  pre_tasks:
    - name: Install Ansible Galaxy requirements
      community.general.ansible_galaxy_install:
        type: collection
        requirements_file: requirements.yml
      ignore_errors: true

    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/Desktop/Screenshots
        - ~/.config
        - ~/.local/bin

  roles:
    - role: homebrew
      tags: ['homebrew', 'packages']

    - role: macos-defaults
      tags: ['macos', 'defaults', 'system']

    - role: dotfiles
      tags: ['dotfiles', 'shell', 'git']

    - role: applications
      tags: ['apps', 'configuration']

  post_tasks:
    - name: Update Homebrew and cleanup
      homebrew:
        update_homebrew: true
        upgrade_all: true
      tags: ['homebrew', 'cleanup']

    - name: Restart affected services
      shell: |
        killall Dock
        killall SystemUIServer
        killall Finder
      ignore_errors: true
      tags: ['restart']

    - name: Display completion message
      debug:
        msg: |
          ============================================================
          macOS setup completed successfully!
          ============================================================

          Next steps:
          1. Restart your terminal or source your shell configuration
          2. Sign into applications that require authentication
          3. Configure app-specific preferences as needed
          4. Set up SSH keys and Git credentials

          You may need to log out and log back in for all changes to take effect.
          ============================================================
      tags: ['always']