---
- name: Configure VS Code settings
  copy:
    content: |
      {
        "editor.fontFamily": "Hack Nerd Font, Monaco, 'Courier New', monospace",
        "editor.fontSize": 14,
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.detectIndentation": true,
        "editor.renderWhitespace": "boundary",
        "editor.rulers": [80, 120],
        "workbench.colorTheme": "Default Dark+",
        "terminal.integrated.fontFamily": "Hack Nerd Font",
        "git.enableSmartCommit": true,
        "git.confirmSync": false,
        "files.autoSave": "onFocusChange",
        "editor.formatOnSave": true
      }
    dest: "~/Library/Application Support/Code/User/settings.json"
    mode: '0644'
    backup: true
  tags: ['applications', 'vscode']

- name: Set iTerm2 to use Intone Mono Nerd Font
  osx_defaults:
    domain: com.googlecode.iterm2
    key: "New Bookmarks.0.Normal Font"
    type: string
    value: "IntoneMono Nerd Font 18"
  tags: ['applications', 'iterm2']

- name: Create iTerm2 color schemes directory
  file:
    path: ~/Downloads/iTerm2-ColorSchemes
    state: directory
    mode: '0755'
  tags: ['applications', 'iterm2']

- name: Download 0x96f iTerm2 color scheme for manual import
  get_url:
    url: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/0x96f.itermcolors
    dest: ~/Downloads/iTerm2-ColorSchemes/0x96f.itermcolors
    mode: '0644'
  tags: ['applications', 'iterm2']

- name: Remove incorrect color scheme file from DynamicProfiles
  file:
    path: ~/Library/Application Support/iTerm2/DynamicProfiles/0x96f.itermcolors
    state: absent
  tags: ['applications', 'iterm2']

- name: Set 0x96f iTerm2 color scheme via shell
  shell: |
    # Set background color (dark gray)
    defaults write com.googlecode.iterm2 "New Bookmarks.0.Background Color" -dict \
      "Red Component" 0.0588235 \
      "Green Component" 0.0588235 \
      "Blue Component" 0.0588235

    # Set foreground color (light gray)
    defaults write com.googlecode.iterm2 "New Bookmarks.0.Foreground Color" -dict \
      "Red Component" 0.6 \
      "Green Component" 0.6 \
      "Blue Component" 0.6

    # Set cursor color
    defaults write com.googlecode.iterm2 "New Bookmarks.0.Cursor Color" -dict \
      "Red Component" 0.94902 \
      "Green Component" 0.375977 \
      "Blue Component" 0.063919

    # Set bold color
    defaults write com.googlecode.iterm2 "New Bookmarks.0.Bold Color" -dict \
      "Red Component" 0.8 \
      "Green Component" 0.8 \
      "Blue Component" 0.8
  ignore_errors: true
  tags: ['applications', 'iterm2']

# Commented out due to osx_defaults module not supporting dict type
# - name: Configure iTerm2 color scheme
#   osx_defaults:
#     domain: com.googlecode.iterm2
#     key: "New Bookmarks.0.Foreground Color"
#     type: dict
#     value:
#       Red Component: 0.73
#       Green Component: 0.73
#       Blue Component: 0.73
#   tags: ['applications', 'iterm2']

- name: Enable Docker at startup
  shell: |
    if [ -d "/Applications/Docker.app" ]; then
      osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Docker.app", hidden:false}'
    fi
  ignore_errors: true
  tags: ['applications', 'docker']

- name: Configure 1Password to start at login
  shell: |
    if [ -d "/Applications/1Password 7 - Password Manager.app" ]; then
      osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/1Password 7 - Password Manager.app", hidden:false}'
    fi
  ignore_errors: true
  tags: ['applications', '1password']